var foodItemsList = [
	{
		"type" : ["dal"],
		"name" : "Chana Dal",
		"price" : "70",
		"quantity" : "1Kg",
		"pic" : "resources/images/chana-dal.jpg",
	},
	{
		"type" : ["dal"],
		"name" : "Toor Dal",
		"quantity" : "1Kg",
		"price" : "80",
		"pic" : "resources/images/toor-dal.jpeg",
	},
	{
		"type" : ["dal"],
		"name" : "Moong Dal",
		"quantity" : "1Kg",
		"price" : "80",
		"pic" : "resources/images/moong-dal.jpg",
	},
	{
		"type" : ["dal"],
		"name" : "Masoor Dal",
		"quantity" : "1Kg",
		"price" : "90",
		"pic" : "resources/images/masoor-dal.jpg",
	},
	{
		"type" : ["dal"],
		"name" : "Urad Dal",
		"quantity" : "1Kg",
		"price" : "90",
		"pic" : "resources/images/urad-dal.jpg",
	},
	{
		"type" : ["atta"],
		"name" : "Aashirwaad Multigarins Atta",
		"quantity" : "5Kg",
		"price" : "235",
		"pic" : "resources/images/aashirwaad-multigrain.jpg",
	},
	{
		"type" : ["atta"],
		"name" : "Aashirwaad Superior Atta",
		"quantity" : "10Kg",
		"price" : "305",
		"pic" : "resources/images/aashirwad-superior.jpg",
	},
	{
		"type" : ["atta"],
		"name" : "Pillsbury Multigrain Atta",
		"quantity" : "5Kg",
		"price" : "250",
		"pic" : "resources/images/pillsbury-multigrain.jpg",
	},
	{
		"type" : ["atta"],
		"name" : "Pillsbury Atta",
		"quantity" : "10Kg",
		"price" : "330",
		"pic" : "resources/images/pillsbury-atta.jpg",
	}
]