var foodItemsList = [
	{
		"type" : ["foodgrain"],
		"name" : "Chana Dal",
		"price" : 70,
		"weight" : "1Kg",
		"pic" : "resources/images/chana-dal.jpg",
	},
	{
		"type" : ["foodgrain"],
		"name" : "Toor Dal",
		"weight" : "1Kg",
		"price" : 80,
		"pic" : "resources/images/toor-dal.jpeg",
	},
	{
		"type" : ["foodgrain"],
		"name" : "Moong Dal",
		"weight" : "1Kg",
		"price" : 80,
		"pic" : "resources/images/moong-dal.jpg",
	},
	{
		"type" : ["foodgrain"],
		"name" : "Masoor Dal",
		"weight" : "1Kg",
		"price" : 90,
		"pic" : "resources/images/masoor-dal.jpg",
	},
	{
		"type" : ["foodgrain"],
		"name" : "Urad Dal",
		"weight" : "1Kg",
		"price" : 90,
		"pic" : "resources/images/urad-dal.jpg",
	},
	{
		"type" : ["fruit"],
		"name" : "Banana",
		"weight" : "1Kg",
		"price" : 60,
		"pic" : "resources/images/banana.jpg",
	},
	{
		"type" : ["fruit"],
		"name" : "Apple",
		"weight" : "1Kg",
		"price" : 100,
		"pic" : "resources/images/apple.png",
	},
	{
		"type" : ["fruit"],
		"name" : "Carrot",
		"weight" : "1Kg",
		"price" : 62,
		"pic" : "resources/images/carrot.jpg",
	},
	{
		"type" : ["fruit"],
		"name" : "Cauliflower",
		"weight" : "1Kg",
		"price" : 30,
		"pic" : "resources/images/cauliflower.jpg",
	},
	{
		"type" : ["fruit"],
		"name" : "Potato",
		"weight" : "1Kg",
		"price" : 20,
		"pic" : "resources/images/potato.jpg",
	},
	{
		"type" : ["fruit"],
		"name" : "Onion",
		"weight" : "1Kg",
		"price" : 15,
		"pic" : "resources/images/onions.jpg",
	},
	{
		"type" : ["fruit"],
		"name" : "Tomato",
		"weight" : "1Kg",
		"price" : 18,
		"pic" : "resources/images/tomato.jpg",
	},
	{
		"type" : ["foodgrain"],
		"name" : "Pillsbury Atta",
		"weight" : "10Kg",
		"price" : 330,
		"pic" : "resources/images/pillsbury-atta.jpg",
	},
	{
		"type" : ["foodgrain"],
		"name" : "Pillsbury Multigrain Atta",
		"weight" : "5Kg",
		"price" : 250,
		"pic" : "resources/images/pillsbury-multigrain.jpg",
	},
	{
		"type" : ["foodgrain"],
		"name" : "Aashirwaad Multigarins Atta",
		"weight" : "5Kg",
		"price" : 235,
		"pic" : "resources/images/aashirwaad-multigrain.jpg",
	},
	{
		"type" : ["foodgrain"],
		"name" : "Aashirwaad Superior Atta",
		"weight" : "10Kg",
		"price" : 305,
		"pic" : "resources/images/aashirwad-superior.jpg",
	}
]